### PR TITLE
Loads RSA keys with Passphrase

### LINKED ISSUE #11: Load RSA keys with passphrase
I have RSA keys that are encrypted using a password. How would I go about loading them from disk and using them? Currently, when trying to load them, gives this error:

```
iex(11)> ExPublicKey.load("/Users/Psy/crap/crypto/testkey.pem")
{:error,
 %FunctionClauseError{arity: 1, function: :pem_entry_decode,
  module: :public_key},
 [{:public_key, :pem_entry_decode,
   [{:RSAPrivateKey,
     <<69, 103, 57, 185, 26, 114, 20, 34, 100, 84, 103, 123, 157, 128, 197, 116,
       174, 125, 94, 20, 234, 243, 138, 198, 8, 108, 207, 220, 65, 70, 93, 198,
       113, 84, 163, 100, 154, 48, 60, 9, 237, 3, ...>>,
     {'AES-128-CBC',
      <<44, 86, 151, 113, 171, 22, 39, 28, 21, 99, 173, 229, 4, 100, 138,
        3>>}}], [file: 'public_key.erl', line: 140]},
  {ExPublicKey, :load_pem_entry, 1, [file: 'lib/ex_public_key.ex', line: 63]},
  {ExPublicKey, :loads, 1, [file: 'lib/ex_public_key.ex', line: 49]},
  {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 670]},
  {:elixir, :erl_eval, 3, [file: 'src/elixir.erl', line: 229]},
  {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 217]},
  {IEx.Evaluator, :handle_eval, 6, [file: 'lib/iex/evaluator.ex', line: 182]},
  {IEx.Evaluator, :do_eval, 4, [file: 'lib/iex/evaluator.ex', line: 175]},
  {IEx.Evaluator, :eval, 4, [file: 'lib/iex/evaluator.ex', line: 155]},
  {IEx.Evaluator, :loop, 3, [file: 'lib/iex/evaluator.ex', line: 61]}, 
  {IEx.Evaluator, :init, 4, [file: 'lib/iex/evaluator.ex', line: 21]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

### PR DESCRIPTION
**Pull request by sheharyarn**
These methods accept an additional `passphrase` argument (defaults to `nil`), which if present, tries to decode the entry using the supplied passphrase:

 - `load`
 - `load!`
 - `loads`
 - `loads!`
 - `load_pem_entry`

Also converts the passphrase to charlist if it's a string to make it work with the underlying erlang `:public_key` module.

Closes #11.

### CODE REVIEW

**Comment by sheharyarn** [comment]
This is weird, raises error on `String.to_charlist/1`. Also doesn't fail locally.

@ntrepid8 Can you restart the build and see if it happens again?

**Comment by sheharyarn** [comment]
Okay turns out it used to be `String.to_char_list` in elixir 1.2.x and previous versions. Updated the minimum elixir requirement to 1.3.

File: mix.exs [hunk 1]
```diff
@@ -5,7 +5,7 @@ defmodule ExCrypto.Mixfile do
     [app: :ex_crypto,
      version: "0.5.0",
      name: "ExCrypto",
-     elixir: ">= 1.0.0",
+     elixir: ">= 1.3.0",
```
Comment (ntrepid8) [inline mix.exs]: Does this PR use any functions that require Elixir 1.3 or higher? If so that's cool, if not I'd like to leave this requirement where it is so the library works with projects that haven't migrated to the newer version yet.

**Comment by ntrepid8** [comment]
Mostly this looks great! Thanks for the PR, just had the one question about the Elixir version requirement.

**Comment by sheharyarn** [comment]
@ntrepid8 Yeah, I'm using `String.to_charlist/1` which didn't exist before Elixir 1.3 (it used to be `String.to_char_list/1`).

**Comment by ntrepid8** [comment]
I'll try and get this packaged up and uploaded to hex.pm this afternoon. I think it will go up as `v0.6.0`.

**Comment by ntrepid8** [comment]
Released:
- https://hex.pm/packages/ex_crypto/0.6.0
- https://github.com/ntrepid8/ex_crypto/releases/tag/v0.6.0

Thanks again!
